[project]
name = "project-starter"
version = "0.1.0"
requires-python = ">=3.11"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.mypy]
python_version = "3.11"
strict = true
disable_error_code = ["misc"]