name: CI
on: [push, pull_request]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic pytest ruff black mypy
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Type check
        run: mypy .
      - name: Tests
        run: pytest -q
